# Generated by Django 3.1.7 on 2021-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=250)),
                ('shop_location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_image', models.ImageField(upload_to='product')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.category_details')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.shop_details')),
            ],
        ),
    ]
